# Header
menu:
  Blog: /#blog
  About: /about
  Blogroll: /blogroll

# Site favicon
favicon: /favicon.png

# Site logo
# logo: /avatar.png

# Enable Fancybox
fancybox: true

# Enable Mathjax
mathjax: true

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false

## Enable highlight
highlight: false